### ISSUE TITLE
Crystallizer model: failing to solve at some input combinations

### ISSUE THREAD

**Issue by Zhuoran29** [watertap-org/watertap#1014]
### Description

I did some parametric analysis on the crystallizer model by varying the following variables in `\watertap\unit_models\tests\test_crystallizer.py`:
Feed salinity: `feed_mass_frac_NaCl` 
Yield: `crystallizer_yield`

The model is most likely to fail at initialization stage when  `feed_mass_frac_NaCl`  is between 0.14 to 0.19 (140 to 190 g/L):
![1682529161(1)](https://user-images.githubusercontent.com/43014540/234651891-c6bc7adb-14c9-400b-8560-09020eb4268f.png)

Looks like to me the initialization routine or scaling factors is not generalized enough, I'm wondering if the team have an idea of which part of the initialization should be reconsidered?

### Expected Behavior

I expect the model to be solvable within the range I mentioned above. As can be seen from the figure below (fixing `crystallizer_yield=0.8`), the model solves well on both side of the failing range, and the trend indicates that those results are valid.

![1682529441](https://user-images.githubusercontent.com/43014540/234653044-0974e0b2-ff6f-4419-8989-91926a007084.png)

### Steps to Reproduce

One example of the failing case is:

1. Change the input variables:
 At line 61 of `test_crystallizer.py`, specify `feed_mass_frac_NaCl = 0.15` (original value is 0.2126)
2. Run the tester:
`pytest D:\Python\watertap-0.8.0\watertap\unit_models\tests\test_crystallizer.py`
3. Get error:
`FAILED watertap/unit_models/tests/test_crystallizer.py::TestCrystallization::test_initialize - idaes.core.util.exceptions.InitializationError: Unit model fs.unit failed to initialize`

### Environment

- OS:
Edition: Windows 11 Pro
Version:	22H2
OS build:	22621.1555

- Python: v3.8
- WaterTAP: v0.8

**Comment by adam-a-a** [comment]
@OOAmusat I tagged you on this issue as an assignee since this is regarding the NaCl crystallizer model.

**Comment by OOAmusat** [comment]
@Zhuoran29 @adam-a-a Please find attached a text file that runs your case study over the entire range. It works fine within the entire region you are interested in; this is the graph for the region shown in your above example.

[cryst_zhouran.txt](https://github.com/watertap-org/watertap/files/11337622/cryst_zhouran.txt)

![image](https://user-images.githubusercontent.com/47539353/234712805-70cb789d-ec4a-4ca8-8a7b-6ddac6d7f4e2.png)

It turns out that an inital point of 0.15/40% is just a really poor point for the solver (not sure why yet). Starting from 0.16/40% works fine, even with the default scaling values. Once the initial solution runs fine, the rest of the runs work without issues.

**Comment by Zhuoran29** [comment]
@OOAmusat Thanks very much for your prompt response and the script. This is super helpful to know that I need to take care of the feed mass flow rate.

**Comment by adam-a-a** [comment]
Thanks for looking at this, @OOAmusat! Glad to hear it had nothing to do with the model itself.
