### ISSUE TITLE
Move examples out of package

### ISSUE THREAD

**Issue by wigging** [watertap-org/watertap#1043]
As discussed in the [Discussions forum](https://github.com/watertap-org/watertap/discussions/809), I propose moving the examples from `watertap/watertap/examples` to `watertap/examples`. The examples remain in this repository but they are moved out of the package. Instead of creating one big pull request, I'll submit several small pull requests which move one group of examples at a time. This pull request can be closed once all the examples have been moved.

The list below represents the structure of the `watertap/watertap/examples` directory. I will check off the corresponding item in the list as the examples are moved to `watertap/examples`.

- [ ] chemistry
- [ ] custom_model_demo
- [ ] edb
- [ ] flowsheets
    - [ ] RO_with_energy_recovery
    - [ ] case_studies
    - [ ] crystallization
    - [ ] electrodialysis
    - [ ] full_treatment_train
    - [ ] ion_exchange
    - [ ] lsrro
    - [ ] oaro

**Comment by lbianchi-lbl** [comment]
Just to be on the safe side and avoid misunderstandings:

- **This would be a significant change with little to none objective added value and  wide-reaching negative impact on many project deliverables for which AMO Subtask 2.3 and 2.4 are directly responsible**
- Since AFAIK none of this has been approved by the subtask leads or key contributors, I don't think this should go forward
- While there's no direct way to prevent further activity from individual contributors outside of these subtasks, I would discourage it as it would mean for us (i.e. AMO Subtask 2.4) having to deal with PRs that we will not be able (or willing) to merge

While creating discussions about this type of things is OK (assuming one has extra time to dedicate to this in addition to their project deliverables, which is unfortunately very limited for many of us including myself), it doesn't make much sense to proceed with any concrete steps that impact other subtasks (in this case, AMO Subtasks 2.3 and 2.4) without the explicit and unambiguous agreement from those subtasks.

About this specific case, since I haven't seen any changes in the motivation or project needs for doing this (or, indeed, any willingness to engage with the several points described by me in significant detail), the original points I made on PR #805 still stand and therefore I've personally decided to avoid participating in #809 as, at this point, I wasn't able to justify _any_ amount of time spent on this as useful for the project.

Unfortunately, my opinion is that the situation seems to have gotten to the point where the value to the project has started becoming _negative_, as multiple people from the affected subtasks are having to invest time and resources to engage with this so that further negative impact on their deliverables (and the project as a whole) is limited.

I hope this makes things clearer and hopefully less ambiguous for why, in my opinion, **we would be unable and unwilling to merge any PR connected with this proposed change** to the repository structure at this point in time. Again, to clarify, this is my personal point of view as a key contributor in the subtask that would be most affected by this. I think the best way forward would probably be an offline discussion to ensure that our efforts are aligned with each other's responsibilities and overall project goals.

**Comment by dangunter** [comment]
I agree since this breaks the Watertap UI, it can't go forward. And there is no time to refactor how the UI functions, as we have lots of other work to do and little time to do it. 

Perhaps a better tack would be to work on the documentation to help people navigate the structure as it stands? I am sure the current documentation is incomplete and misleading, and help there would be greatly appreciated.
