### ISSUE TITLE
Failures in OLI API Jupyter notebooks: name 'state_vars' is not defined in OLI tutorial

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1298]
### Description

Trying out the new version of the OLI API, I started out by trying to run the OLI tutorial that we have. state_vars is never created in the example, so a `NameError` is returned, and the code example won't work.

### Expected Behavior

Running the OLI tutorial code should work as expected and return results.

I would also expect tests to catch that the code wouldn't work. I thought all of our notebooks were tested, but perhaps because this is tied to OLI, this one has to be treated differently.

### Steps to Reproduce

Try running the OLI tutorial, assuming you have log-in credentials setup in some fashion.

**Comment by veccp** [comment]
This has been fixed in the latest push to #1296. In the mean time, the occurrence of `source_water` can be replaced with `state_vars` or vice versa.

**Comment by lbianchi-lbl** [comment]
I'll add that the reason why this wasn't caught is that essentially all of the code in this notebook is skipped if an authenticated OLI API client is not available, i.e. our regular CI.

Conversely, in the repository used for testing with authenticated clients does not run Jupyter notebooks. If we think it'd be worth it, we should be able to add this functionality without too much trouble.

**Comment by lbianchi-lbl** [comment]
I've added notebook testing to the OLI API checks. To run it together with the default pytest job, specify one or more notebook paths to the `notebooks-to-run` input, e.g.

```
gh workflow run -R watertap-org/oli-api-ci oli-api.yml -F pr=1296 -F notebooks-to-test=tutorials/incorporating_oli_calculations.ipynb
```

However, there's no (easy) way to test whether the notebook runs without error because all cells are skipped (i.e. the same thing that happens when notebook tests are run in this repository where the authenticated client is not available), or because all code in each cell was run in its entirety (i.e. as expected with a successfully authenticated client).

Therefore, I propose to make the following changes to each notebook using the OLI API:

1. Remove the logic that checks for each cell whether the authenticated client is available (i.e. make it so that the notebook will raise exceptions unless an authenticated client is available)
2.  Exclude the notebook from being run at all where the authenticated client is not available (i.e. CI workflows in this repository)

**Comment by veccp** [comment]
@lbianchi-lbl Is there any logic that needs to be added to the notebook itself to make it work with the OLI API testing workflow?

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl Is there any logic that needs to be added to the notebook itself to make it work with the OLI API testing workflow?

Aside from removing the `if credential_manager:` checks, there needs to be a way to read credentials in a non-interactive way without hardcoding the credentials in the notebook. I think the same environment-based mechanism used for the pytest fixtures would be a good starting point, e.g.

```py
import os

credential_manager = CredentialManager(
    # username="",
    # password="",
    auth_url="Not required when using access keys",
    # this example reads credentials from the environment. Adapt it to your preferred way of supplying credentials by commenting/uncommenting keyword arguments as needed
    root_url=os.environ["OLI_API_ROOT_URL"],
    access_keys=[os.environ["OLI_API_KEY"]],
)
```

(I'm afraid the helper text above is not very helpful, so feel free to treat it as a placeholder)
