### ISSUE TITLE
typo in https://watertap.readthedocs.io/en/0.11.0/technical_reference/unit_models/nanofiltration_0D.html

### ISSUE THREAD

**Issue by krisvillez** [watertap-org/watertap#1331]
### Description

In [https://watertap.readthedocs.io/en/0.11.0/technical_reference/unit_models/nanofiltration_0D.html ](url), under the text "Outlet water and salt fluxes:", the second equation has a left-side term "J_in,t,j". This should probably be "J_out,t,j"

### Expected Behavior

Change left-side term of second equation under "Outlet water and salt fluxes:" from "J_in,t,j" to "J_out,t,j"

### Environment

- OS:
- Python:
- WaterTAP:

**Comment by ksbeattie** [comment]
This is part of #1248

**Comment by adam-a-a** [comment]
Hi @krisvillez - thanks for noticing that. This technical reference actually corresponds to an early nanofiltration model which we recently marked for deletion. Our RO model can be configured to do the same thing that this model did (i.e., use the Kedem-Katchalsky model), and we have other formulations for nanofiltration too. Thus, we will more likely remove this technical reference rather than correct it. The following issue provides a checklist of this and other items within WaterTAP that are marked for deletion:  #1248
