### ISSUE TITLE
Add membrane area to inputs page of OARO GUI

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1407]
Membrane area should be available to specify as a fixed or free variable in the OARO GUI. Even though we typically like to optimize membrane area per stage, we should still allow the user the option to fix membrane area as desired. 

The default option for membrane area would be to have it set as a free variable. @luohezhiming does this sound reasonable to you?

**Comment by luohezhiming** [comment]
@adam-a-a Since the OARO flowhseet is an optimization flowsheet and the membrane area is a decision vairbale, it is always free. And we fixed `recovery_mass_phase_comp` for each OARO units for ease of initialization instead of  membrane_area. So, the membrane area is always a free varible, even export as an input variable, it is still free.
If we choose to fix membrane area at the begining, then the system might be hard to pass initialization. Anyhow, the major problem is this is an optimization problem, and we choose membrane area as a decision variable, so user cannot fix it and it is meaningless to fix it at the begining

**Comment by adam-a-a** [comment]
@luohezhiming By default, we have rendered it a free variable--yes. But that is not a requirement--just a preferred approach to better ensure convergence to a solution. We have other "difficult" models in the GUI that may fail to solve when the user fiddles with the inputs in a certain way, but we still allow the flexibility to do so. 

Thus, even though the user could get an error back instead of a successful solve when changing this, we should include area in the inputs section, labeled as a free var be default, which lines up with what we both were saying, I think. Then the user could optionally change to a fixed variable after the initial solve or even do a sweep on area, even though it would be risky.

**Comment by luohezhiming** [comment]
@adam-a-a The GUI fully depends on the flowsheet, even though we export the membrane area as an input variable, I believe it will only be shown as a free variable (with default valuess), we cannot make it as fixed or do sweep analysis according to my previous experience. Since the GUI is just a UI interface, it cannot implement some analysis beyond the capability of original flowsheet. So unless we choose to solve another optimization problem where membrane_area is fixed, otherwise it will only be shown as a free variable I guess, but I'll confirm by another attempt

**Comment by adam-a-a** [comment]
I understand how the GUI works and have implemented my suggestion for another case, which is why I am 99% sure that what I am suggesting is feasible and should be done. The first step is setting `is_input=True` for stage area. In fact, all the decision vars should be exposed in this way--at least the inlet pressures and areas. @MarcusHolly - any thoughts on this since you have worked with exporting to GUI more than most of us?

**Comment by adam-a-a** [comment]
@luohezhiming check out the nanofiltration example in the GUI-either one should do (bypass or without bypass). I worked on these, and you can see how "NF pump pressure" and "NF area" are displayed on the input page as "Free" variables since these are the decision variables in the associated flowsheet: 
![image](https://github.com/watertap-org/watertap/assets/22691844/7059525c-ad3c-45a9-a3c5-b0282c103d5d)

**Comment by MarcusHolly** [comment]
> @luohezhiming By default, we have rendered it a free variable--yes. But that is not a requirement--just a preferred approach to better ensure convergence to a solution. We have other "difficult" models in the GUI that may fail to solve when the user fiddles with the inputs in a certain way, but we still allow the flexibility to do so.
> 
> Thus, even though the user could get an error back instead of a successful solve when changing this, we should include area in the inputs section, labeled as a free var be default, which lines up with what we both were saying, I think. Then the user could optionally change to a fixed variable after the initial solve or even do a sweep on area, even though it would be risky.

I agree with what was said here. Even if the solve fails most of the time when the user changes the membrane area from "free" to "fixed", I think it's still fine to include. However, if the solve fails like 99.9% of the time that membrane area is set to "fixed" I can see an argument for not including it.

**Comment by luohezhiming** [comment]
@adam-a-a @MarcusHolly After some attempts, I figured out that it is feasible to add those free variables as input and we can vary it through simulation. Since previously I am trying to input flow_vol and concentration instead of flow_mass, I found them are free and will not change anything if we fixed them because they will directly go back to the default setting of flow_mass no matter what values we fixed. So I assume the same situation would happen with membrane area. However, the flow_vol and concentration problem could come from the calculate_state function, so it is a different thing. I am sorry and already put up a new PR #1411 to add membrane area and inlet pressure as two other inputs.
