### ISSUE TITLE
Type Error on EDB local test

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#219]
After installing a fresh proteuslib environment, I get the following error running pytest. This error seems localized to the EDB. No other tests seem to fail when running individually.

=========================================================================== test session starts ===========================================================================
platform win32 -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: C:\Users\1pi\projects\proteuslib, configfile: pytest.ini
plugins: cov-2.12.1
collected 109 items / 1 error / 108 selected

================================================================================= ERRORS ==================================================================================
_______________________________________________________ ERROR collecting proteuslib/tests/test_pure_water_pH_edb.py _______________________________________________________
test_pure_water_pH_edb.py:75: in <module>
    class TestPureWaterEdb(TestPureWater):
test_pure_water_pH_edb.py:79: in TestPureWaterEdb
    thermo_config = get_thermo_config(g_edb)
test_pure_water_pH_edb.py:51: in get_thermo_config
    return base.idaes_config
E   AttributeError: 'NoneType' object has no attribute 'idaes_config'

---------- coverage: platform win32, python 3.8.10-final-0 -----------

**Comment by aladshaw3** [comment]
@dangunter I still get this error even if I reload the edb using the command line tools.

**Comment by dangunter** [comment]
Ok, let's just comment out the test for now and I can revisit in a couple of weeks.

**Comment by aladshaw3** [comment]
I haven't gotten this error anymore. Has this been addressed? @dangunter

**Comment by aladshaw3** [comment]
@dangunter  This is the same error now in PR #239

**Comment by lbianchi-lbl** [comment]
@aladshaw3 @dangunter I've looked a bit more in depth into `test_pure_water_pH` and `test_pure_water_pH_edb` and I think the error might be related to what to me looks like a more general design issue with the subclassing of the `TestPureWater` test class.

In pytest, it's generally recommended against using subclasses for functionality that's beyond their intended use as a way to group related test functions. The preferred way to implement a specialization of a more general case, especially when test data is involved, is to use fixtures. Any fixture can be overridden at any scope (session, module, class, function) simply by defining another fixture function with the same name, with the one "closest" to the test function being the one used to generate the value passed to the test function (i.e. with essentially the same semantics as overriding methods in subclasses).

From what I understand from the code, it should be relatively straightforward to refactor `test_pure_water_pH` and `test_pure_water_pH_edb` so that it uses fixtures instead of dynamically assigned class attributes to access the test data. Are you aware of any reason why this approach might not work?

**Comment by aladshaw3** [comment]
@lbianchi-lbl  I don't understand how this would cause the error to appear in Windows, but not in Linux.

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl I don't understand how this would cause the error to appear in Windows, but not in Linux.

@aladshaw3 the difference between Windows and Linux is that, in the current GitHub Actions setup, a real MongoDB instance is available on Linux but not on Windows. So, essentially, Windows (on GHA) = "there's no real MongoDB available".

I think the core of the issue is in the class definition of `TestPureWaterEdb` starting at line 79. That code is executed at import time, and should be skipped unless `g_edb` is truth-y, which in turn depends on whether the `ElectrolyteDB.can_connect()` check succeeds. On GHA with Windows, I'd expect `ElectrolyteDB.can_connect()` to return `False`, but the fact that the code at line 79 gets executed (as shown by the tests failing there) suggests that the check might be returning `True` even though it shouldn't.

In all this, I think that running code at import time should be avoided if possible, especially if it involves performing highly non-local actions like connecting to an external DB instance, and especially if it's done within pytest (since pytest will import modules in way that's not necessarily what one might expect, e.g. re: the order in which modules are imported).

I'm not 100% sure that using fixtures would fix this particular problem, but it would make it more predictable since the check would be done at runtime rather than at import time. Using fixtures (that are managed and dispatched by pytest at runtime) instead of setting class attributes at import time on a pytest test class (something that pytest is not "expecting") seems to me like a better choice, (again, especially when an external database is involved).

**Comment by dangunter** [comment]
I'm fine with wrapping the mongodb test in a function.
