### ISSUE TITLE
Renaming "solute" in zero-order models and omitting water recovery from input data

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#347]
Not all components will be solutes, so the naming of `removal_frac_mass_solute` can be changed to `removal_frac_mass_comp`. From this, `recovery_frac_mass_H2O` would no longer be needed in YAML files to load into unit models. Instead it could be calculated as 1 - `removal_frac_mass_comp['H2O']`. 

Changing this would alter our WT3 migration work and could slow down our effort for WT3 and AMO model implementation, so it might be best to consider addressing this issue once models are in place.

See the conversation in PR #340 for more details on the discussion.

**Comment by andrewlee94** [comment]
I think there are actually two part to this:

1. Should water be treated the same way as all other species - i.e. have a removal instead of recovery? At the moment water needs its own material balances as they are formatted (slightly) differently, which in turn means that the remaining balances need to be indexed over everything that isn't water which we currently call "solutes"
2. If we stay with treating water differently, is there a better name than "solutes" - we already have entrained/suspended solids in some cases which are not strictly solutes, and we may see other liquids or entrained gases in future.

Either way, there is a bit of work in this, as any renaming would affect all the YAML files, as well as the core code for the unit models and all the tests.

**Comment by bknueven** [comment]
It sounds like we something we should do *after* the unit models are in place, given how many open PRs we have at the moment.

**Comment by dangunter** [comment]
@TimBartholomew will bring this up with @bknueven
