### ISSUE TITLE
Relax Codecov Requirements

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#514]
Our current code coverage is great, but the checks for new PRs may be too strict. Some PRs are failing the checks by missing coverage, even though their coverage is over 90% (examples: PR #505 and PR #516).

**Comment by bknueven** [comment]
Right now we have the converage requirement set to "auto", which creates a ratchet for coverage. Now that we're hovering around 94-95%, maybe we should decide on a target number (e.g., 90% or 95%) that we're happy with.

**Comment by aladshaw3** [comment]
I think 95% is a little crazy to try and consistently hit (too many different error states that one might have to check for). I would be in favor of 90 % (or as low as 85 %).

**Comment by lbianchi-lbl** [comment]
Following the discussion during the dev call:

- To try to find the optimal annoyance/strictness tradeoff, we can adopt different criteria for patch coverage and project coverage
  -  In general, project coverage is the number we should be more protective of (i.e. if a PR is lowering the coverage for the entire project to a significant degree (>1%), we would probably want the check to fail)
- I'm going to open a PR to specify a `tolerance` parameter to the Codecov configuration so that the check passes if the number is within X% of the target
