### ISSUE TITLE
Condense IX_prop_pack and use ion (now MCAS) property package

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#599]
Eliminate IX prop_pack and refine unit model as needed. 
Task list:

- [x] add equivalent concentrations/flows to ion prop pack
- [x] move reference ion config options to IX unit model (in anticipation for future dev)
- [ ] consider separating pumps from IX model
- [ ] consider incorporating 0D CV Block

**Comment by aladshaw3** [comment]
I have a few other suggestions for improvement as well:

- [x] Allow for a set or list of target ions (instead of only 1 ion getting removed)
    - Need config option for target ion to change to a list
    - Use "Extended Langmuir" model for multi-component, competitive ion-exchange 
    - Would also mean that there is now a set of `equ_cap` vars for each species being captured 

- [x] Reformulate the current Langmuir constraint to avoid divide by zero issues for high concentrations/capacities 
    - Current formulation may have poor convergence behavior

- [x] Swap out the current `eq_resin_eq_capacity` inequality constraint for a site balance (with associated available site vars)
    - Ion exchange occurs at specific sites and is dependent on availability of those sites
    - Create an `avail_sites` var, then add a constraint for new var using `max_cap` and `equ_cap`
    - Constraint:  `max_cap` = `avail_sites` + `equ_cap`
    - This should help avoid current issues with `equ_cap` being greater than `max_cap` without needing to use an inequality constraint in the system.

**Comment by lbianchi-lbl** [comment]
@kurbansitterley any updates on this? We were wondering whether this can be closed or updated to only included outstanding items (if any).

**Comment by kurbansitterley** [comment]
This can be closed. We don't have plans for multi component model at this time so the outstanding item from @aladshaw3 and the 0D CV is incorporated in the #998.
