### ISSUE TITLE
Modify cost_electrodialysis function not to use _get_performance_contents

### ISSUE THREAD

**Issue by luohezhiming** [watertap-org/watertap#613]
The `_get_performance_contents` function shouldn't be used for calculating the costing for the electrodialysis unit model, it typically only accounts for obtaining system performance. I suggest to change it to directly use `power_electrical` .

**Comment by aladshaw3** [comment]
This is fine to change, however, this will require the addition of an `Enum` for electrodialysis because the 0D and 1D electrodialysis models have slightly different variables for `power_electrical`.

In the 0D model, you can directly use `power_electrical` indexed at the specified time point.

In the 1D model, electrical power variable is an integrated variable over the length of the domain. The equivalent for `power_electrical` in the 1D model is called `power_electrical_x` and is indexed by time and position. The actual total electrical power is located at the last position point in the domain. 

This was the reason behind using the `_get_performance_contents` function, because that function just returns a dictionary to the proper electrical power variable for each model (regardless of 0D or 1D). Thus, the same function call can be used for either without the need for the `Enum` in the costing package.

**Comment by adam-a-a** [comment]
Another thing we could do is add `power_electrical` to the 1d model and set it equal to the last element of `power_electrical_x` so that both models have the same name for the same var, and we can then just point to `power_electrical`.
