### ISSUE TITLE
Add support for Python 3.10

### ISSUE THREAD

**Issue by bknueven** [watertap-org/watertap#615]
I see IDAES now tests against Python 3.10. We should do the same, and if for some reason we have an incompatibility we should address it.

**Comment by lbianchi-lbl** [comment]
I think this is a good idea. To keep the number of CI jobs under check, we should consider dropping support for Python 3.7.

**EDIT**: From the [numpy supported version table](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table), 3.7 seems to be outside of the official support window since December 2021.
