### ISSUE TITLE
Isothermal pump model should be updated

### ISSUE THREAD

**Issue by TimBartholomew** [watertap-org/watertap#651]
Currently the isothermal pump model - inherits an IDAES pump model, then deletes the energy balance, then writes a constraint making the temperatures equal.

This is an issue because all property packages must support enthalpy to use this pump model, when it isn't necessary. This is because the deleted energy balance requires it.

**Comment by adam-a-a** [comment]
One thing I think we should consider is bringing in the code for IDAES' pressure exchanger and adding necessary lines to prevent errors. More specifically, I think the pump model should be able to work regardless of the EnergyBalanceType set on a property model. That is, the pump model won't work when EnergyBalanceType is set to None, and the `work` variable is not created on the control volume when enthalpy balances are not considered. The pump model shouldn't have such restrictions. It should only require pressure in, pressure out, flowrate, and efficiency, and the `work` term should always be available in a pump unit regardless of EnergyBalanceType.

The error we get when using a property model with EnergyBalanceType.none is due to the PressureExchanger setting `self.work_mechanical = Reference(self.control_volume.work[:])`. Since `work` doesn't exist in this instance, an exception is raised. I suggest we simply add a line before this checking whether `work` exists; if it does not exist, then create the `work` variable then and there.

The same concept will apply for the reversible pump (ERD).

**Comment by andrewlee94** [comment]
@adam-a-a I would go a step further and suggest someone make a PR to IDAES proposing the change you suggested (i.e. if EnergyBalanceType is None in the control volume and the ThermodynamicAssumption in Pump, the unit model should create the `work` variable. Make sure to document why this is needed in the PR.

**Comment by adam-a-a** [comment]
@andrewlee94 I think we can do that. However, should we go beyond those conditions (i.e., EnergyBalanceType is None in the control volume and the ThermodynamicAssumption in Pump)? I am not sure yet whether the exception is only restricted to an EnergyBalanceType of none-- would have to take a closer look at the ControlVolume.

**Comment by adam-a-a** [comment]
Looking at the `pressure_changer` code again, I think the solution would be to have a `work` term on the `control_volume` no matter what the EnergyBalanceType is, since a pressure changer should have a work term, unless it is a valve or something other than a pump or compressor.
Thus, change the following: 
` self.work_mechanical = Reference(self.control_volume.work[:])`

to something like the following: 
```
        if not hasattr(self.control_volume, 'work'):
            units = self.config.property_package.get_metadata().get_derived_units
            self.control_volume.work= Var(
                self.flowsheet().time,
                domain=Reals,
                initialize=0.0,
                doc="Work transferred into control volume",
                units=units("power"),)
        self.work_mechanical = Reference(self.control_volume.work[:])
```

Perhaps the suggestion is too broad and requires additional conditions, but I do think we should build the `work` term on the control_volume because many models try to set scaling factors for `control_volume.work` so doing anything else could lead to a lot of unnecessary fixes across the board.

EDIT: In fact, even `ThermodynamicAssumption.adiabatic` sets work = 0, so I **_think_** we can always have a work term no matter what.

**Comment by andrewlee94** [comment]
@adam-a-a What do you mean when you refer to building the `work` term regardless? Do you expect the control volume to do it for you, are are you suggesting that the pressure changer model should add the work variable to the control volume if it wasn't built by the energy balance?

I would argue against the former (as what does a work term mean with out some form of energy constraint), but you might be able to convince me of the second (however I would probably want to see more extensive discussion o the effects and error checking). The pump is an exceptional circumstance where the energy is calculated on flow and pressure change rather than by an energy balance.

Also, I would not rely on the adiabatic case for an argument either - for one it is incorrectly named (adiabatic means no heat transfer, which all our pressure changers assume), and what is a pressure changer with do work transfer?

**Comment by adam-a-a** [comment]
@andrewlee94 

> Do you expect the control volume to do it for you, are are you suggesting that the pressure changer model should add the work variable to the control volume if it wasn't built by the energy balance?

**I am suggesting that the pressure changer model should add the work variable to the control volume if it wasn't build by the energy balance.**

> Also, I would not rely on the adiabatic case for an argument either - for one it is incorrectly named (adiabatic means no heat transfer, which all our pressure changers assume), and what is a pressure changer with do work transfer?

**I noticed this as well. The adiabatic case should be Q = 0 rather than W = 0, but I looked past this and just took note of the fact that work was still considered as a variable. I would say though, although this might go beyond the scope of the current issue, couldn't a valve or pipe fitting be considered as a pressure changer without work? For example, see "Modeling Other Pressure Changers" [here](https://processdesign.mccormick.northwestern.edu/index.php/Pressure_changer).** 

After further reflection, I think it would be wise to be more exclusive rather than inclusive, which is the opposite of what I was thinking previously. That is, I would propose a conditional directly before `work_mechanical` variable is created via a Reference to `control_volume.work` that would check for the following criteria to be true and subsequently create the work variable on the control volume if all were true:
1) the work variable does NOT exist on the control volume
2) EnergyBalanceType is None
3) ThermodynamicAssumption is Pump

Currently, it seems control volumes only support None type and enthalpyTotal energy balance types, so one could argue that we don't need the "EnergyBalanceType is None" check. However, like I said, I'd rather be exclusive rather than inclusive and keep the check. Checking that "ThermodynamicAssumption is Pump" would resolve the issue for pumps and compressors, which is what we'd want, continuing with the exclusive approach rather than allowing the work term to always be created. Things could _possibly_ go wrong with the isothermal Thermodynamic assumption and I'd rather implement code that touches less things and could be easily extended as needed in the future.

**Comment by adam-a-a** [comment]
I expect to do this PR on IDAES, but I assigned everyone else to this issue only to grab your attention as these changes will be especially relevant for you, not to push any work into your lap @TimBartholomew @arao53 @avdudchenko

**Comment by andrewlee94** [comment]
@adam-a-a That sounds like a good solution, and I would include the check for EnergyBalanceType for protection against future expansion.

Regarding the adiabatic pressure changer - the primary issue is the name is incorrect, but as you said that is beyond the scope of this PR. And regarding a pipe, there is still work being done. In this case it is work done by the fluid to overcome friction (and thus not "useful work", but it is still work).

**Comment by adam-a-a** [comment]
I put up a PR in IDAES to address the issue, at least to the extent needed for now: https://github.com/IDAES/idaes-pse/pull/925

**Comment by adam-a-a** [comment]
> I put up a PR in IDAES to address the issue, at least to the extent needed for now: https://github.com/IDAES/idaes-pse/pull/925

The PR was merged in IDAES, so the next thing to do is set the IDAES dependency to the relative tag and adjust our pump unit.

**Comment by ksbeattie** [comment]
The documentation for idaes-pse will be updated here: https://github.com/IDAES/idaes-pse/issues/927

**Comment by lbibl** [comment]
Being addressed by https://github.com/IDAES/idaes-pse/pull/1035

**Comment by lbibl** [comment]
https://github.com/IDAES/idaes-pse/pull/1035 is merged to complete the change made to allow pump work calculated without an energy balance constraint.   This issue could be closed unless others catch anything else.
