### ISSUE TITLE
Support an intensive stateblock

### ISSUE THREAD

**Issue by TimBartholomew** [watertap-org/watertap#666]
Currently all stateblocks are extensive (i.e. they have the mass/mole flowrates), it would be nice to support state blocks that are intensive.

There are a couple clear use cases for intensive state blocks (i.e. they only have intensive state variables like concentrations and calculate intensive properties like osmotic pressure, density, etc):

1. When users just want to calculate some properties for a specified water composition. Many water treatment software programs support this - where users just provide concentrations and the other intensive properties can be calculated.
2. When model developers only want the intensive variables at some location in the unit model. This is actually really common, the biggest example is in the RO model we have interfacial membrane concentrations that vary from the bulk concentration. 

The way we are currently handling these use cases for where an intensive stateblock would be useful is the following:
1. The users have to set the volumetric flowrate to some value (could be anything, as long as its well scaled) and solve the block - this probably works most of the time but it does skip the initialization step (since users aren't fixing the extensive state variables) and it requires the users to set something that they don't care about. If the user needs to use initialization, they would have to first provide good guesses for the extensive variables, initialize, then fix the intensive concentrations, and then solve. Both options aren't necessarily bad or that hard, but it could be confusing to the user.
2. The model developer creates the constraints to calculate the intensive variables they are interested in (i.e. relating the bulk concentration to the interface concentration), then they also have to create a constraint to provide the extensive information (i.e. making the bulk flowrate equal the the interface flowrate). The downside with this is that it creates the extensive variables that are unnecessary and could be confusing to the user because they might think these extensive variables mean something - but they don't, they are completely unnecessary and are not used in mass or energy balances. Also from with discussions with multiple new developers this concept and the reasoning why we need this constraint is very confusing.

**Comment by TimBartholomew** [comment]
Initially, I thought supporting intensive state blocks would be a ton of work, but I think there is a relatively easy way to do this.

We could create a new method that is like `build_state_block()`, let's call it `build_intensive_state_block()`. This method could provide a configuration argument for `is_intensive = True`, when its default is always `False`.

This boolean can then be used in the property package build, where if it is intensive then instead of building the extensive flow state variables it directly builds the intensive concentration. As long as all the other intensive variables can be created from the intensive state variables then all the other properties can be built on demand as normal.

Creating these intensive state variables I think cleverly solves the problem of that usually a property will eventually be built that require the original extensive state variables, instead since these variables are already built the method that creates them won't be called and so it won't go further to the extensive state variables.

For the seawater and NaCl property package the clear option for what the intensive state variables should be is the mass fraction. All other intensive variables are written as a function of the mass fraction, temperature, and pressure or other properties that are only a function of them.

Scaling can also be appropriately handled this way, the model developer would just have to make sure that the intensive properties are based on the scaling factors from the intensive state variable (i.e. mass fraction).

The challenge I haven't thought through is how this impacts the initialization routines not only at the property package level but higher up as well.

**Comment by andrewlee94** [comment]
@TimBartholomew The biggest issue with something like this is standardization; there would now be two ways of doing things, meaning there now need to be checks to see which type of StateBlock something is. I would suggest this is too significant a difference to be handled by a binary construction argument and that it would warrant an entire new class (or perhaps more likely have the intensive class derive from StateBlock and the extensive class derive from the intensive one).

First however, I have to ask if this is really a problem? For your first use case, the user can just set arbitrary flowrates (e.g. 1), so I don't see that as a huge issue. For your second use case, if the conditions vary from the bulk flow, how are you calculating these conditions without some sort of material/energy balances (i.e. don't you basically have/need the extensive information anyway)?

**Comment by lbibl** [comment]
Here are some of my thoughts: 1) per Andrew's concern on essentially creating an whole new class, we may go for creating two property packages of the described kinds and passing them to unit blocks via two configurations, instead of distinguishing them in one property blocks?  2) w.r.t. if this really a problem- for the described scenario with an "arbitrary flow rate", it essentially made an equation system with infinite number of solutions (flow rate becomes a free variable). The current property block sets flow rate as state variables so we must assign it a value to implement, but it is only a "fake" state variable in the sense that it doesn't set any state of the material being solved.  Instead the state here was carried by a fixed concentration or fraction, from which other variables are calculated.  This can be computationally ok but physically of no sense.  There are some physical cases where it causes confusions like Tim suggested. For example, in some fluid mechanical models, it hypothesized a static fluid film at the interface of two phases, where all rates should be set zero (are we actually do this?  to set the flow rate as zero and still solve other intensive variables?).  Or imagine, one just wanna describe a bunch of properties of a solution in a beaker.  All is static in these cases and "rates" variables should be out of the picture.  3) In so far as "intensive" and "extensive" are to distinguish if a property varies with material size and if the goal is to take out all "rate" variables, I would suggest "dynamic" vs "static" apply better here.  In fact, in a "static property block" , we may set volume as one of the state variables, and both intensive (e.g., fraction, concentration) and extensive (e.g., mass, molarity) properties can be computed.

**Comment by TimBartholomew** [comment]
After discussions with @andrewlee94 @lbibl @adam-a-a, the hack proposed here is not enough. We'd need to make structural changes to identify extensive or intensive state blocks or even separate them completely.

Its unclear whether this amount of effort would be worth it.
