### ISSUE TITLE
Hydraulic diameter calculation method for spacer-filled channels 

### ISSUE THREAD

**Issue by lbibl** [watertap-org/watertap#842]
### Description

So far at least RO- and electrodialysis- related models concern the calculation of hydraulic diameter (d_h) for fluid in spacer-filled channels. There are several reported equation forms to handle this depending on the assumptions about fluid conditions, channel and spacer geometries.  In ED (electrodialysis), I am including two methods,  with one requiring the parameter of spacer_volume_specific_area (S_v).  This S_v-based equation can be derived to the equation used in RO units with specifying a particular spacer type.   @adam-a-a suggested considering unifying these methods in all RO, ED and potentially other models .   This issue tracks the decision and actions on this matter. 

#

**Comment by lbibl** [comment]
@adam-a-a This issue was opened when I added a spacer-surface-area based method to calculate the hydraulic diameter of spacers in ED systems.   You suggested opening this issue to track if we want RO and ED line up on this matter.  If we want,  we can add the same method onto RO (or other units concerning a spacer hydraulic diameter), although I think it's ok to make no changes if every unit is working properly.  How would you like to close this issue?

**Comment by adam-a-a** [comment]
@lbibl Just catching up with old issues now. So, I get your point of including the more general equation. However, one reason I opted against that was because knowing the specific surface area of the spacer and having to specify it upfront seemed more cumbersome than specifying the channel height and spacer porosity, which are more readily known. We probably could add the more general form of the equation for RO through a separate config option. However, I consider this low priority for now and would propose keeping the issue open as a reminder, even if it gets kicked down the road some more.

**Comment by lbibl** [comment]
@adam-a-a : I really think things are good as what they are now and this issue can be closed.  Will act upon your agreement.

**Comment by lbibl** [comment]
No action is identified to be necessary at this point.
