### ISSUE TITLE
File location of unit model specific property packages that are not universally applicable

### ISSUE THREAD

**Issue by hunterbarber** [watertap-org/watertap#892]
### Description

This issue is created for discussion on the best method of housing the unit model specific property packages

### Motivation

Some property packages such as those for electrocoagulation and (soon to be implemented) SOP are only valid when used with specific unit models. To have these within the same folder location as generic property packages may be misleading for their use in larger flowsheets. 

### Possible Implementation

Options:
- Leave as is, have these located in the same property_package folder
- Move location of files to a more logical place and leave files as is
- Move the unique calculations invalidating the universality of the property package into a separate callable file, call these within a generic universal property package (this allows for the same property package to be used across a diverse technology treatment train but requires the most effort)

### Additional Context

TODO: itemize the specific property or feature within each property package that is unit model specific, then determine if these are separable or generalizable

**Comment by adam-a-a** [comment]
One issue I see with reorganizing is that certain property models could be unit-specific now but evolve later on to be more generalizable, in which case you'd have to move your prop model back to a generalizable folder after previously moving to a case-specific folder. 

For example, what is now the MCAS property package was formerly the ion_DSPMDE property package, which I designed specifically for the NF DPSM-DE model. However, we later realized it could be used more generically since there was overlap with other units like ED, IX, and GAC. 

IMHO, I would opt to slow down on these types of refactoring efforts and focus on bringing in new capabilities, models, analyses, documentation, and refinement that focuses on model stability/functionality. 

To resolve the issue, I would just ensure that prop models are named in a standard way to distinguish specific from general, have docstrings at the top of prop models spelling out whether the model was designed specifically for a given unit or was intended to be more generic, and ensure that documentation exists on readthedocs for each.

**Comment by hunterbarber** [comment]
> One issue I see with reorganizing is that certain property models could be unit-specific now but evolve later on to be more generalizable, in which case you'd have to move your prop model back to a generalizable folder after previously moving to a case-specific folder.
> 
> For example, what is now the MCAS property package was formerly the ion_DSPMDE property package, which I designed specifically for the NF DPSM-DE model. However, we later realized it could be used more generically since there was overlap with other units like ED, IX, and GAC.
> 
> IMHO, I would opt to slow down on these types of refactoring efforts and focus on bringing in new capabilities, models, analyses, documentation, and refinement that focuses on model stability/functionality.
> 
> To resolve the issue, I would just ensure that prop models are named in a standard way to distinguish specific from general, have docstrings at the top of prop models spelling out whether the model was designed specifically for a given unit or was intended to be more generic, and ensure that documentation exists on readthedocs for each.

@adam-a-a I think a naming convention prefix or something similar is a good distinction, as well as clear documentation. Basically, anyway to show a property package may only be used within a state block of a specific unit model and similarly that a unit model only supports a singular property package is an improvement from the current ambiguity.

**Comment by hunterbarber** [comment]
Probably best to leave repo organization as is to avoid the need for revision later due to the potential of refactoring.
