### ISSUE TITLE
Review ZO costing for surface discharge and deep well injection

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#959]
### Description

There _might_ be a potential bug regarding costing of the following zero order models: surface discharge and deep well injection.

An academic user reported that she was getting LCOW values on the order of 10**-7 $/m3. I will try to get more information, but this is worth a look.

### Expected Behavior

We don't expect cost results to be that low. While we make no promises about default values used for ZO models, a result that low just seems like we _might be_ calculating things incorrectly in cost relationships, or the defaults are bad.

### Steps to Reproduce

NA

### Environment

NA

**Comment by MarcusHolly** [comment]
@adam-a-a @bknueven I might've identified the problem here. I made a simple flowsheet (feed -> deep well injection -> product), and computed the LCOW. It seems like there might be an issue with how `m.fs.costing.base_currency` is set up because it is estimating a cost on the order of 10^-7 lower than the $2018. Running the simulation file should reflect this discrepancy (I can't attach the file here since the .py file type is not supported apparently, so I can send my file through Slack if anyone wants it). And this issue is not exclusive to deep well injection, I've observed this discrepancy in multiple pass-through and siso unit models, so it might exist in other places as well.

I'm not sure how to go about resolving this issue, but I just figured I could point someone who would know what to do in the right direction.

**Comment by adam-a-a** [comment]
After discussing with @kurbansitterley and @andrewlee94  , they reminded us that LCOW was calculated with units of MUSD/m3, which would explain the unexpected order of magnitude. This is set by the `base_currency` parameter in the zero order costing package, which loads `base_currency` from `watertap/data/techno_economic/default_case_study.yaml`.
