### ISSUE TITLE
sweep files for flowsheet examples writing NaN values

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#987]
### Description

@MichaelPesce discovered that running any of the multi_sweep files for zero-order flowsheet examples resulted in NaN values being written to CSVs. Previously, this was not the case, and we need to (1) fix the issue and (2) add testing to catch this in the future.
For example, I tried running `watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/suboxic_activated_sludge_process/multi_sweep.py` and these were the results that I got:
![image](https://user-images.githubusercontent.com/22691844/228960182-14e93a12-7e88-469d-a48f-c915d64b88a4.png)

### Expected Behavior

parameter_sweep usage for flowsheet examples should write actual values, not NaNs.

### Steps to Reproduce

skipping

### Environment

skipping

**Comment by bknueven** [comment]
After running `git-bisect` I determined this issue was introduced in #807, commit eb26d538.

**Comment by bknueven** [comment]
The breaking commit in #807 is 7dd05713f30f04240ddefc21690fa76354e496f2

**Comment by bknueven** [comment]
After digging in, I found the root of the issue.

#807 changed the function signature of most of the flowsheet `solve` methods. However, it did *not* update the `optimize_kwargs` in the multi_sweep modules.

This meant that the calls to `solve` were failing due to bad arguments. The parameter sweep tool is too broad in its exception handling -- in part because lots of things *might* cause a particular call to solve to fail. Not sure yet how to address the larger issue in the parameter sweep tool.
